### ISSUE TITLE
Make model information exportable

### ISSUE THREAD

**Issue by rob-heath** [cpmarvin/lnetd_qt#13]
Make model information, network links and network demand exportable.

**Comment by cpmarvin** [comment]
hey Rob. 

Thanks for the suggestion. I'm not which part you are referring to. Is the request to export Model information as png,pdf or something else? And are the 4 fields "Network Nodes,Network Links,Network Demands, Network Failed Demands" the only one you want them in png/pdf ?

Thx.

**Comment by rob-heath** [comment]
Was thinking about CSV export for the network demand mostly.

**Comment by cpmarvin** [comment]
@rob-heath an alternative would be to use the export demands json file and convert it to csv using an online conversion tool (https://www.convertcsv.com/json-to-csv.htm)

I will make the model information exported via a pdf file to include:
- nr of nodes/link/demands
- network density
- network diameter
- node degree
- all shortest paths between all nodes
- all backup paths between nodes

This is quite cpu intensive so will need to see how it goes. most likely in 0.1.5 release

**Comment by cpmarvin** [comment]
for this topology 

![image](https://user-images.githubusercontent.com/20742720/150782285-f25d183e-ea26-4398-a97c-f5bbc327976f.png)

it looks like this 
`
{
    "Connected Network": true,
    "Connectivity Node Degree": [
        [
            "lon1",
            3
        ],
        [
            "mad",
            3
        ],
        [
            "lon2",
            2
        ],
        [
            "par",
            2
        ],
        [
            "nyc",
            1
        ],
        [
            "qas",
            1
        ]
    ],
    "Network Density": 0.4,
    "Network Diameter": 3,
    "Number of Links": 6,
    "Number of Nodes": 6,
    "paths": [
        {
            "ecmp_paths": 1,
            "note": "valid",
            "path_metric": 10,
            "source": "lon1",
            "target": "lon2"
        },
etc
`

**Comment by cpmarvin** [comment]
included in new release
