### ISSUE TITLE
Visibility enhancement - group attribute

### ISSUE THREAD

**Issue by rob-heath** [cpmarvin/lnetd_qt#14]
Provide the ability to tag a node and the corresponding links to a group. Provide the ability to display selected groups and hide the unselected nodes.

**Comment by cpmarvin** [comment]
for now , group and ungroup nodes is possible. Not sure about the use case for hiding the other nodes as this will break the model. Maybe group nodes that you don't need in a group rather than hide them will be best. 
give it a go and let me know if it works for you or not.

**Comment by cpmarvin** [comment]
something like this for now

![image](https://user-images.githubusercontent.com/20742720/148123975-851e6766-db8a-4ba3-b868-948ca8e799ca.png)
