### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by mnanduri** [cpmarvin/lnetd_qt#2]
Is there a requirements.txt for this? running into issues figuring out which package is required.

**Comment by cpmarvin** [comment]
will update soon , in the meantime if on win or mac you can download the binary here : https://github.com/cpmarvin/lnetd_qt/releases/tag/v0.1.2

**Comment by mnanduri** [comment]
Thank you. I will try it on a Mac.
 I was trying to run it on a Ubuntu 18.04 machine.
